### ISSUE TITLE
How to create new templates

### ISSUE THREAD

**Issue by 99bits** [SN-RECIT-formation-a-distance/html-bootstrap-editor-showcase#1]
Thank you for this amazing project.

I would like to create my own templates and wondering how that can be done.
Is it possible to use some sort of visual layout tool to create the templates and then export to be used in the editor showcase?

Merci Beaucoup

**Comment by gustavobazzo** [comment]
Hello 99bits,

Thank you for your comment.

Soon we will publish a new version of the plugin so that users will be able to create their own templates. These user templates will be displayed in the same template area and users will be able to export them.

Regarding the showcase, users can have their own.
You can download this repository [https://github.com/SN-RECIT-formation-a-distance/html-bootstrap-editor-showcase](https://github.com/SN-RECIT-formation-a-distance/html-bootstrap-editor-showcase) to host and build your own showcase.
